quarkus.application.name=notification-service
quarkus.http.port=8081

%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=sus_user
%dev.quarkus.datasource.password=sus_pass
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/sus_queue_db

%dev.rabbitmq-host=localhost
%dev.rabbitmq-port=5672
%dev.rabbitmq-username=guest
%dev.rabbitmq-password=guest

%dev.mp.messaging.incoming.queue-events.host=${rabbitmq-host}
%dev.mp.messaging.incoming.queue-events.port=${rabbitmq-port}
%dev.mp.messaging.incoming.queue-events.username=${rabbitmq-username}
%dev.mp.messaging.incoming.queue-events.password=${rabbitmq-password}

%dev.mp.messaging.incoming.solicitation-denied-events.host=${rabbitmq-host}
%dev.mp.messaging.incoming.solicitation-denied-events.port=${rabbitmq-port}
%dev.mp.messaging.incoming.solicitation-denied-events.username=${rabbitmq-username}
%dev.mp.messaging.incoming.solicitation-denied-events.password=${rabbitmq-password}

%dev.mp.messaging.incoming.solicitation-devolved-events.host=${rabbitmq-host}
%dev.mp.messaging.incoming.solicitation-devolved-events.port=${rabbitmq-port}
%dev.mp.messaging.incoming.solicitation-devolved-events.username=${rabbitmq-username}
%dev.mp.messaging.incoming.solicitation-devolved-events.password=${rabbitmq-password}

%dev.mp.messaging.incoming.appointment-confirmed-events.host=${rabbitmq-host}
%dev.mp.messaging.incoming.appointment-confirmed-events.port=${rabbitmq-port}
%dev.mp.messaging.incoming.appointment-confirmed-events.username=${rabbitmq-username}
%dev.mp.messaging.incoming.appointment-confirmed-events.password=${rabbitmq-password}

%dev.mp.messaging.incoming.appointment-no-slot-events.host=${rabbitmq-host}
%dev.mp.messaging.incoming.appointment-no-slot-events.port=${rabbitmq-port}
%dev.mp.messaging.incoming.appointment-no-slot-events.username=${rabbitmq-username}
%dev.mp.messaging.incoming.appointment-no-slot-events.password=${rabbitmq-password}

%dev.mp.messaging.incoming.appointment-rescheduled-events.host=${rabbitmq-host}
%dev.mp.messaging.incoming.appointment-rescheduled-events.port=${rabbitmq-port}
%dev.mp.messaging.incoming.appointment-rescheduled-events.username=${rabbitmq-username}
%dev.mp.messaging.incoming.appointment-rescheduled-events.password=${rabbitmq-password}

%dev.mp.messaging.incoming.appointment-cancelled-events.host=${rabbitmq-host}
%dev.mp.messaging.incoming.appointment-cancelled-events.port=${rabbitmq-port}
%dev.mp.messaging.incoming.appointment-cancelled-events.username=${rabbitmq-username}
%dev.mp.messaging.incoming.appointment-cancelled-events.password=${rabbitmq-password}

%dev.mp.messaging.incoming.appointment-expired-events.host=${rabbitmq-host}
%dev.mp.messaging.incoming.appointment-expired-events.port=${rabbitmq-port}
%dev.mp.messaging.incoming.appointment-expired-events.username=${rabbitmq-username}
%dev.mp.messaging.incoming.appointment-expired-events.password=${rabbitmq-password}

%dev.quarkus.log.level=INFO
%dev.quarkus.log.category."br.com.sus".level=DEBUG

%dev.quarkus.swagger-ui.always-include=true

%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:sus_user}
%prod.quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:sus_pass}
%prod.quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://postgres:5432/sus_queue_db}
%prod.mp.messaging.incoming.queue-events.host=${RABBITMQ_HOST:rabbitmq}
%prod.mp.messaging.incoming.queue-events.port=${RABBITMQ_PORT:5672}
%prod.mp.messaging.incoming.queue-events.username=${RABBITMQ_USERNAME:admin}
%prod.mp.messaging.incoming.queue-events.password=${RABBITMQ_PASSWORD:admin}

%prod.mp.messaging.incoming.solicitation-denied-events.host=${RABBITMQ_HOST:rabbitmq}
%prod.mp.messaging.incoming.solicitation-denied-events.port=${RABBITMQ_PORT:5672}
%prod.mp.messaging.incoming.solicitation-denied-events.username=${RABBITMQ_USERNAME:admin}
%prod.mp.messaging.incoming.solicitation-denied-events.password=${RABBITMQ_PASSWORD:admin}

%prod.mp.messaging.incoming.solicitation-devolved-events.host=${RABBITMQ_HOST:rabbitmq}
%prod.mp.messaging.incoming.solicitation-devolved-events.port=${RABBITMQ_PORT:5672}
%prod.mp.messaging.incoming.solicitation-devolved-events.username=${RABBITMQ_USERNAME:admin}
%prod.mp.messaging.incoming.solicitation-devolved-events.password=${RABBITMQ_PASSWORD:admin}

%prod.mp.messaging.incoming.appointment-confirmed-events.host=${RABBITMQ_HOST:rabbitmq}
%prod.mp.messaging.incoming.appointment-confirmed-events.port=${RABBITMQ_PORT:5672}
%prod.mp.messaging.incoming.appointment-confirmed-events.username=${RABBITMQ_USERNAME:admin}
%prod.mp.messaging.incoming.appointment-confirmed-events.password=${RABBITMQ_PASSWORD:admin}

%prod.mp.messaging.incoming.appointment-no-slot-events.host=${RABBITMQ_HOST:rabbitmq}
%prod.mp.messaging.incoming.appointment-no-slot-events.port=${RABBITMQ_PORT:5672}
%prod.mp.messaging.incoming.appointment-no-slot-events.username=${RABBITMQ_USERNAME:admin}
%prod.mp.messaging.incoming.appointment-no-slot-events.password=${RABBITMQ_PASSWORD:admin}

%prod.mp.messaging.incoming.appointment-rescheduled-events.host=${RABBITMQ_HOST:rabbitmq}
%prod.mp.messaging.incoming.appointment-rescheduled-events.port=${RABBITMQ_PORT:5672}
%prod.mp.messaging.incoming.appointment-rescheduled-events.username=${RABBITMQ_USERNAME:admin}
%prod.mp.messaging.incoming.appointment-rescheduled-events.password=${RABBITMQ_PASSWORD:admin}

%prod.mp.messaging.incoming.appointment-cancelled-events.host=${RABBITMQ_HOST:rabbitmq}
%prod.mp.messaging.incoming.appointment-cancelled-events.port=${RABBITMQ_PORT:5672}
%prod.mp.messaging.incoming.appointment-cancelled-events.username=${RABBITMQ_USERNAME:admin}
%prod.mp.messaging.incoming.appointment-cancelled-events.password=${RABBITMQ_PASSWORD:admin}

%prod.mp.messaging.incoming.appointment-expired-events.host=${RABBITMQ_HOST:rabbitmq}
%prod.mp.messaging.incoming.appointment-expired-events.port=${RABBITMQ_PORT:5672}
%prod.mp.messaging.incoming.appointment-expired-events.username=${RABBITMQ_USERNAME:admin}
%prod.mp.messaging.incoming.appointment-expired-events.password=${RABBITMQ_PASSWORD:admin}

mp.messaging.incoming.queue-events.connector=smallrye-rabbitmq
mp.messaging.incoming.queue-events.queue.name=notification.queue.events
mp.messaging.incoming.queue-events.exchange.name=sus.queue.exchange
mp.messaging.incoming.queue-events.exchange.type=direct
mp.messaging.incoming.queue-events.routing-keys=patient.registered,patient.called,priority.updated,patient.cancelled,patient.reinstated

mp.messaging.incoming.solicitation-denied-events.connector=smallrye-rabbitmq
mp.messaging.incoming.solicitation-denied-events.queue.name=notification.solicitation.denied
mp.messaging.incoming.solicitation-denied-events.exchange.name=sus.regulacao.exchange
mp.messaging.incoming.solicitation-denied-events.exchange.type=direct
mp.messaging.incoming.solicitation-denied-events.routing-keys=solicitation.denied

mp.messaging.incoming.solicitation-devolved-events.connector=smallrye-rabbitmq
mp.messaging.incoming.solicitation-devolved-events.queue.name=notification.solicitation.devolved
mp.messaging.incoming.solicitation-devolved-events.exchange.name=sus.regulacao.exchange
mp.messaging.incoming.solicitation-devolved-events.exchange.type=direct
mp.messaging.incoming.solicitation-devolved-events.routing-keys=solicitation.devolved

mp.messaging.incoming.appointment-confirmed-events.connector=smallrye-rabbitmq
mp.messaging.incoming.appointment-confirmed-events.queue.name=notification.appointment.confirmed
mp.messaging.incoming.appointment-confirmed-events.exchange.name=sus.agendamento.exchange
mp.messaging.incoming.appointment-confirmed-events.exchange.type=direct
mp.messaging.incoming.appointment-confirmed-events.routing-keys=appointment.confirmed

mp.messaging.incoming.appointment-no-slot-events.connector=smallrye-rabbitmq
mp.messaging.incoming.appointment-no-slot-events.queue.name=notification.appointment.no_slot
mp.messaging.incoming.appointment-no-slot-events.exchange.name=sus.agendamento.exchange
mp.messaging.incoming.appointment-no-slot-events.exchange.type=direct
mp.messaging.incoming.appointment-no-slot-events.routing-keys=appointment.no_slot

mp.messaging.incoming.appointment-rescheduled-events.connector=smallrye-rabbitmq
mp.messaging.incoming.appointment-rescheduled-events.queue.name=notification.appointment.rescheduled
mp.messaging.incoming.appointment-rescheduled-events.exchange.name=sus.agendamento.exchange
mp.messaging.incoming.appointment-rescheduled-events.exchange.type=direct
mp.messaging.incoming.appointment-rescheduled-events.routing-keys=appointment.rescheduled

mp.messaging.incoming.appointment-cancelled-events.connector=smallrye-rabbitmq
mp.messaging.incoming.appointment-cancelled-events.queue.name=notification.appointment.cancelled
mp.messaging.incoming.appointment-cancelled-events.exchange.name=sus.agendamento.exchange
mp.messaging.incoming.appointment-cancelled-events.exchange.type=direct
mp.messaging.incoming.appointment-cancelled-events.routing-keys=appointment.cancelled

mp.messaging.incoming.appointment-expired-events.connector=smallrye-rabbitmq
mp.messaging.incoming.appointment-expired-events.queue.name=notification.appointment.expired
mp.messaging.incoming.appointment-expired-events.exchange.name=sus.agendamento.exchange
mp.messaging.incoming.appointment-expired-events.exchange.type=direct
mp.messaging.incoming.appointment-expired-events.routing-keys=appointment.expired

%prod.quarkus.log.level=INFO
%prod.quarkus.log.category."br.com.sus".level=INFO

%prod.quarkus.swagger-ui.always-include=true

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.sql-load-script=no-file
quarkus.hibernate-orm.database.default-schema=notification

quarkus.smallrye-openapi.path=/v3/api-docs
quarkus.swagger-ui.path=/q/swagger-ui
