spring.datasource.url=jdbc:postgresql://localhost:5432/sus_queue_db
spring.datasource.username=sus_user
spring.datasource.password=sus_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.virtual-host=/

spring.jpa.show-sql=true
logging.level.br.com.morbus=DEBUG
