package br.com.sus.notificationservice.model.enums;

public enum ENotificationType {
    PATIENT_REGISTERED, PATIENT_CALLED, PRIORITY_UPDATED, PATIENT_CANCELLED,
    SOLICITATION_DENIED, SOLICITATION_DEVOLVED,
    APPOINTMENT_CONFIRMED, APPOINTMENT_NO_SLOT, APPOINTMENT_RESCHEDULED
}
