package br.com.sus.notificationservice.model.enums;

public enum ENotificationType {
    PATIENT_REGISTERED, PATIENT_CALLED, PRIORITY_UPDATED, PATIENT_CANCELLED, PATIENT_REINSTATED,
    SOLICITATION_DENIED, SOLICITATION_DEVOLVED,
    APPOINTMENT_CONFIRMED, APPOINTMENT_NO_SLOT, APPOINTMENT_RESCHEDULED, APPOINTMENT_CANCELLED, APPOINTMENT_EXPIRED
}
