spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/agendamento_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sus_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sus_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin}
spring.rabbitmq.virtual-host=/

logging.level.br.com.morbus=INFO

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
