schema {
    query: Query
}

type Query {
    disponibilidade(
        procedureId: ID!
        unitId: ID
        dataInicio: String!
        dataFim: String!
    ): [Slot!]!

    agendamentos(
        pacienteId: ID
        unitId: ID
        status: AppointmentStatus
        dateFrom: String
        dateTo: String
    ): [Appointment!]!

    agendamento(id: ID!): Appointment

    grade(unitId: ID!, week: String!): [Schedule!]!
}

type Slot {
    id: ID!
    dataHora: String!
    capacity: Int!
    booked: Int!
    remainingCapacity: Int!
    status: SlotStatus!
    schedule: Schedule!
}

type Schedule {
    id: ID!
    dayOfWeek: String!
    startTime: String!
    endTime: String!
    slotDurationMin: Int!
    capacity: Int!
    active: Boolean!
    unit: HealthUnit!
    provider: Provider
}

type HealthUnit {
    id: ID!
    cnes: String!
    nome: String!
    address: String
    phone: String
}

type Provider {
    id: ID!
    nome: String!
    crm: String
    especialidade: String
}

type Appointment {
    id: ID!
    status: AppointmentStatus!
    expiresAt: String!
    cancellationReason: String
    createdAt: String!
    slot: Slot!
}

enum SlotStatus {
    DISPONIVEL
    RESERVADO
    OCUPADO
    INDISPONIVEL
}

enum AppointmentStatus {
    AGUARDANDO_CONFIRMACAO
    CONFIRMADO
    CANCELADO
    ATENDIDO
    FALTOU
}
